services:
  blog-database:
    image: postgres:16.6
    container_name: blog-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "blog"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

  blog-cache:
    image: redis:7.2.5
    container_name: blog-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

  # nginx:
  #   image: nginx:1.27.3
  #   container_name: blog-backend-nginx
  #   depends_on:
  #     - blog-api-1
  #     - blog-api-2
  #     - blog-api-3
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/api/nginx.conf:ro
  #   networks:
  #     - blog-network

  blog-backend:
    container_name: blog-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - blog-database
      - blog-cache
    environment:
      - DATABASE_URL=postgres://postgres:password@blog-database:5432/blog?sslmode=disable
      - REDIS_URL=redis://blog-cache:6379
    networks:
      - blog-network

networks:
  blog-network:
    name: blog-network
    driver: bridge

volumes:
  blog_data:
    name: blog-data
