services:
  blog-api:
    container_name: blog-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map the host's port 8080 to the container's port 8080
    depends_on:
      - blog-db
      - blog-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@blog-db:5432/blog?sslmode=disable
      - REDIS_URL=redis://blog-redis:6379
    networks:
      - blog-network

  blog-db:
    image: postgres:16.6
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "blog"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

  blog-redis:
    image: redis:7.2.5
    container_name: blog-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

networks:
  blog-network:

volumes:
  blog_db_data:
