services:
  blog-db:
    image: postgres:16.6
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "blog"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

  blog-redis:
    image: redis:7.2.5
    container_name: blog-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - blog-network

  nginx:
    image: nginx:latest
    container_name: blog-backend-nginx
    depends_on:
      - blog-api-1
      - blog-api-2
      - blog-api-3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/api/nginx.conf:ro
    networks:
      - blog-network

  blog-api-1:
    container_name: blog-api-1
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - blog-db
      - blog-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@blog-db:5432/blog?sslmode=disable
      - REDIS_URL=redis://blog-redis:6379
    networks:
      - blog-network
  blog-api-2:
    container_name: blog-api-2
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - blog-db
      - blog-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@blog-db:5432/blog?sslmode=disable
      - REDIS_URL=redis://blog-redis:6379
    networks:
      - blog-network
  blog-api-3:
    container_name: blog-api-3
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - blog-db
      - blog-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@blog-db:5432/blog?sslmode=disable
      - REDIS_URL=redis://blog-redis:6379
    networks:
      - blog-network

networks:
  blog-network:

volumes:
  blog_db_data:
