services:
  blog-web-1:
    container_name: blog-web-1
    restart: on-failure:3
    build:
      context: .
    ports:
      - "5174:5173"
    volumes:
      - .:/app
    networks:
      - blog-network

  blog-web-2:
    container_name: blog-web-2
    restart: on-failure:3
    build:
      context: .
    ports:
      - "5175:5173"
    volumes:
      - .:/app
    networks:
      - blog-network

  blog-web-3:
    container_name: blog-web-3
    restart: on-failure:3
    build:
      context: .
    ports:
      - "5176:5173"
    volumes:
      - .:/app
    networks:
      - blog-network

  nginx:
    image: nginx:latest
    container_name: blog-web-nginx
    depends_on:
      - blog-web-1
      - blog-web-2
      - blog-web-3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/web/nginx.conf:ro
    networks:
      - blog-network

networks:
  blog-network:
